[project]
name = "companion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tino", email = "santinogianninoto@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "paho-mqtt>=2.1.0",
    "python-chess>=1.999",
]

[project.scripts]
companion = "companion:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
